### ISSUE TITLE
Enhancement: Extending Contract Type Identification and DynamoDB Storage for Non-ERC721/ERC1155 Contracts

### ISSUE THREAD

**Issue by kwiss** [ArkProjectNFTs/ark-project#2]
### Description

Our current application is successfully identifying and indexing blockchain contract types for ERC721 and ERC1155. For contracts that aren't of these types, we need to extend the identification process, save them in DynamoDB, and include them in a blacklist to avoid fetching their information multiple times.

### Steps to Reproduce

1. Start the blockchain block indexer.
2. The application starts to index contracts.
3. Observe that non-ERC721 and non-ERC1155 contracts are not indexed and can be fetched multiple times.

### Relevant Code

```rust
// Relevant portion of the existing code
...
// Determine the contract type
if token_uri_result != "null" {
    contract_type = "erc721".to_string();
} else if uri_result != "null" {
    contract_type = "erc1155".to_string();
}
...
if contract_type != "unknown" {
    ...
    match add_collection_item(&dynamo_client, item, &table).await {
        Ok(collection) => {
            println!(
                "Collection successfully added: {:?} {}, type: {}",
                collection, from_address, contract_type
            );
        }
        Err(e) => {
            eprintln!("Error while adding collection: {:?}", e);
        }
    }
}
...
pub async fn add_collection_item(client: &Client, item: Item, table: &String) -> Result<(), Error> {
...
    let contract_type_av = AttributeValue::S(item.contract_type);

    let request = client
        .put_item()
        .table_name(table)
        .item("name", name_av)
        ...
        .item("type", contract_type_av);

    request.send().await?;

    Ok(())
}
```

### Potential Solution

Extend the contract type identification logic to include contracts that aren't ERC721 or ERC1155. Save the identified contract types in DynamoDB with the same data structure, adding any necessary fields (like a flag for blacklisted contracts). Modify the fetch operation to check this blacklist before proceeding.

### Tasks

- [ ] Extend contract type identification logic to include non-ERC721 and non-ERC1155 contracts
- [ ] Modify the add_collection_item function to handle the extended contract types
- [ ] Update DynamoDB structure to include any necessary fields
- [ ] Implement a blacklist feature using DynamoDB
- [ ] Update fetch operation to check blacklist before proceeding

### Additional Context

This modification should reduce redundant operations and optimize the blockchain indexing process.
